#!/bin/sh /etc/rc.common

START=50
STOP=80
USE_PROCD=1

start_service() {
	local n=0
	while [ ! -e /dev/mmd_bidcos ] && [ "$n" -lt 30 ]; do
		sleep 1
		n=$((n + 1))
	done

	[ -e /dev/mmd_bidcos ] || return 1

	procd_open_instance
	procd_set_param command \
		/usr/bin/hmlangw \
		-b -r -1 \
		-s /dev/mmd_bidcos \
		-n PEQ2215760

	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
